---

hostname: mail.example.com
addional_ssl_domains:
  - example.com
local_domains:
  - example.com
open_ports:
  - port: 22
    proto: tcp
    rate_limit:
      timeout: 120
      hitcount: 8
  - port: 25
    proto: tcp
    rate_limit:
      timeout: 120
      hitcount: 8
  - port: 80
    proto: tcp
  - port: 465
    proto: tcp
    rate_limit:
      timeout: 120
      hitcount: 8
  - port: 587
    proto: tcp
    rate_limit:
      timeout: 120
      hitcount: 8
  - port: 993
    proto: tcp
    rate_limit:
      timeout: 120
      hitcount: 8
mail_users:
  - user: user@example.com
    argon2id: '{ARGON2ID}$argon2id$v=19$m=65536,t=3,p=1$salt$hash'
    aliases:
      - root@example.com
      - abuse@example.com
      - postmaster@example.com
users:
  - user: user
    pass: $6$salt$hash
    groups:
      - sudoers
    ssh_key: ssh-rsa pubkey chris@desktop